const fs = require('fs');

const path = require('path');

const apiPath = path.join(__dirname, '..', 'frontend', 'js', 'api.js');

let content = fs.readFileSync(apiPath, 'utf8');

const updatedPoets = `[
  { id:1, name:"Rajan Rai", hindi:"राजन राय", period:"16/08/2005 - Present", color:"#8B1A1A", initials:"रा", category:"contemporary", tags:["founder","contemporary"], isFeatured:true, image:"assets/rajan-rai.png?v=4", speciality:"Philosophical Poetry, Aphorism", bio:"Rajan Rai is the visionary founder of Niharika and a distinguished philosopher-poet. His works primarily explore human potential, existential truth, and self-realisation. Grounded in profound stoicism and intense psychological realism, his writings bridge the chasm between ancient wisdom and modern struggles." },
  { id:2, name:"Kabir Das", hindi:"कबीर दास", period:"1440 - 1518", color:"#C9982A", initials:"क", category:"classical", tags:["classical","bhakti"], isFeatured:true, image:"https://upload.wikimedia.org/wikipedia/commons/9/90/Sant_Kabir.jpg", speciality:"Doha, Nirgun Bhakti", bio:"Kabir Das was a 15th-century Indian mystic poet and saint, whose writings heavily influenced Hinduism's Bhakti movement. His verses are found in Sikhism's scripture Guru Granth Sahib. His 'Dohe' carry timeless wisdom emphasizing the formless (Nirgun) divine, condemning religious hypocrisy and societal dogmas." },
  { id:3, name:"Harivansh Rai Bachchan", hindi:"हरिवंश राय बच्चन", period:"1907 - 2003", color:"#2e7d32", initials:"ह", category:"modern", tags:["modern"], isFeatured:true, image:"https://upload.wikimedia.org/wikipedia/commons/8/8d/Harivansh_Rai_Bachchan.jpg", speciality:"Kavita, Chhayavad-utar", bio:"One of the most acclaimed Hindi poets of the early 20th century, Harivansh Rai Bachchan is celebrated worldwide for 'Madhushala' (1935), a timeless allegorical work. A recipient of the Padma Bhushan and Saraswati Samman, his poetry masterfully weaves optimism, philosophical inquiry, and emotional vulnerability." },
  { id:4, name:"Mirabai", hindi:"मीराबाई", period:"1498 - 1547", color:"#6A0572", initials:"मी", category:"classical", tags:["classical","bhakti"], isFeatured:true, image:"https://upload.wikimedia.org/wikipedia/commons/e/e0/Meerabai.jpg", speciality:"Bhajan, Sagun Bhakti", bio:"Mirabai was a 16th-century Hindu mystic poet and devotee of Lord Krishna. She is a celebrated Bhakti saint, particularly in the North Indian Hindu tradition. Her passionate 'bhajans' explore divine ecstasy, intense spiritual yearning, and fearless rebellion against patriarchal limitations." },
  { id:5, name:"Ramdhari Singh Dinkar", hindi:"रामधारी सिंह दिनकर", period:"1908 - 1974", color:"#1a237e", initials:"दि", category:"modern", tags:["modern","patriotic"], isFeatured:true, image:"https://upload.wikimedia.org/wikipedia/commons/f/ff/Ramdhari_Singh_Dinkar.jpg", speciality:"Rashtriya Kavita, Veer Ras", bio:"Known as the 'Rashtrakavi' (National Poet) for his inspiring patriotic compositions, Dinkar's poetry emerged as a rebellion during the Indian independence movement. His masterpieces like 'Rashmirathi' and 'Kurukshetra' are monumental achievements in modern Hindi literature. He won the Jnanpith Award in 1972." },
  { id:6, name:"Gulzar", hindi:"गुलज़ार", period:"1934 - Present", color:"#37474F", initials:"गु", category:"contemporary", tags:["contemporary","nazm"], isFeatured:true, image:"https://upload.wikimedia.org/wikipedia/commons/2/22/Gulzar_at_an_event_in_Delhi_%28cropped%29.jpg", speciality:"Nazm, Film Lyrics, Triveni", bio:"Sampooran Singh Kalra, popularly known as Gulzar, is an Oscar-winning Indian poet, lyricist, and film director. His 'Nazms' and 'Trivenis' are distinguished by their profound symbolism, surreal imagery, and delicate emotional nuances. He has been awarded the Padma Bhushan, the Sahitya Akademi Award, and the Dadasaheb Phalke." },
  { id:7, name:"Mahadevi Verma", hindi:"महादेवी वर्मा", period:"1907 - 1987", color:"#880E4F", initials:"म", category:"modern", tags:["modern","chhayawad"], isFeatured:false, image:"https://upload.wikimedia.org/wikipedia/commons/0/07/Mahadevi_Verma.jpg", speciality:"Chhayawad Kavita, Virah", bio:"Considered one of the four major pillars of the Chhayawad era in Hindi literature, Mahadevi Verma is often hailed as the 'Modern Meera'. Her intensely emotional poetry focuses on separation (Virah) and nature. She received the Jnanpith Award and the Padma Vibhushan." },
  { id:8, name:"Sumitranandan Pant", hindi:"सुमित्रानंदन पंत", period:"1900 - 1977", color:"#1B5E20", initials:"पं", category:"modern", tags:["modern","chhayawad"], isFeatured:false, image:"https://upload.wikimedia.org/wikipedia/commons/e/ec/Sumitranandan_Pant.jpg", speciality:"Prakriti Kavita, Chhayawad", bio:"A central figure of the Chhayawad literary movement, Pant's poetry is renowned for its romanticism and lush depictions of nature, inspired by his childhood in the Himalayas. The first Hindi poet to receive the Jnanpith Award, he seamlessly blended aesthetics with progressive and philosophical ideas." },
  { id:9, name:"Rahim Das", hindi:"रहीम दास", period:"1556 - 1627", color:"#4E342E", initials:"र", category:"classical", tags:["classical","doha"], isFeatured:false, image:"https://upload.wikimedia.org/wikipedia/commons/5/52/Abdul_Rahim_Khan-I-Khana.jpg", speciality:"Doha, Satsai, Niti Kavya", bio:"Abdul Rahim Khan-i-Khanan, known simply as Rahim, was a poet who lived during the rule of Mughal emperor Akbar, featuring among his 'Navaratnas' (Nine Gems). He wrote profoundly on themes of ethics, human nature, and life's impermanence, drawing from both Islamic and Hindu philosophy." },
  { id:10, name:"Nirala", hindi:"निराला", period:"1896 - 1961", color:"#BF360C", initials:"नि", category:"modern", tags:["modern","chhayawad"], isFeatured:false, image:"https://upload.wikimedia.org/wikipedia/commons/2/23/Suryakant_Tripathi_Nirala.jpg", speciality:"Mukt Chhand, Chhayawad", bio:"Suryakant Tripathi 'Nirala' was a towering figure in the Chhayawad movement, credited with introducing free verse (mukt chhand) to Hindi poetry. His works exhibit a fierce rebel spirit, capturing both cosmic beauty and devastating social realities, defying traditional poetic constraints." },
  { id:11, name:"Jaishankar Prasad", hindi:"जयशंकर प्रसाद", period:"1889 - 1937", color:"#0D47A1", initials:"प्र", category:"classical", tags:["classical","chhayawad"], isFeatured:false, image:"https://upload.wikimedia.org/wikipedia/commons/9/90/Jaishankar_prasad.jpg", speciality:"Mahakavya, Kamayani", bio:"A legendary dramatist and poet, Jaishankar Prasad was the pioneer of the Chhayawad era. His magnum opus, 'Kamayani', is universally acclaimed as the pinnacle of modern Hindi epic poetry, weaving Vedic philosophy, human emotion, and psychological evolution into magnificent verse." },
  { id:12, name:"Dr. Hariom Panwar", hindi:"डॉ. हरिओम पंवार", period:"1956 - Present", color:"#1A237E", initials:"प", category:"contemporary", tags:["contemporary"], isFeatured:false, image:"https://yt3.ggpht.com/ytc/AIdro_nL1O5yq64jH_lq206cOQ5-03U_Vks9Q6yD7uWg1g=s900-c-k-c0x00ffffff-no-rj", speciality:"Kavi Sammelan, Patriotic, Veer Ras", bio:"Dr. Hariom Panwar is a modern stalwart of 'Veer Ras' (heroic poetry) and an iconic voice in Kavi Sammelans. His booming recitations and fiercely patriotic verses focus on national sacrifice, historical pride, and fiery critiques of political apathy." }
]`;

const updatedPoems = `[
  { id:1, text:"A man can do anything,\\nwhen he realises he is a man.", hindi:"एक इंसान सब कुछ कर सकता है,\\nजब वो जान ले कि वो इंसान है।", poet:"Rajan Rai", poetId:1, form:"Aphorism", likes:12400, isRajanQuote:true },
  { id:2, text:"Silence is the loudest answer\\nthe soul ever gives.", hindi:"खामोशी वो सबसे ऊँची आवाज़ है\\nजो आत्मा कभी देती है।", poet:"Rajan Rai", poetId:1, form:"Aphorism", likes:9800, isRajanQuote:true },
  { id:3, text:"Every storm within you\\nis just a sunrise waiting to break.", hindi:"तुम्हारे भीतर का हर तूफ़ान\\nबस एक सूर्योदय है जो उगने की राह देख रहा है।", poet:"Rajan Rai", poetId:1, form:"Nazm", likes:10200, isRajanQuote:true },
  { id:4, text:"The mind that questions itself\\nis already wiser than most.", hindi:"वो मन जो खुद से सवाल करता है,\\nवो पहले से ही अधिकांश से अधिक बुद्धिमान है।", poet:"Rajan Rai", poetId:1, form:"Aphorism", likes:8700, isRajanQuote:true },
  { id:5, text:"Love is not what you feel -\\nit is what you become.", hindi:"प्रेम वो नहीं जो तुम महसूस करते हो -\\nप्रेम वो है जो तुम बन जाते हो।", poet:"Rajan Rai", poetId:1, form:"Aphorism", likes:11500, isRajanQuote:true },
  { id:6, text:"मन रे तन कागद का पुतला,\\nलागे बूंद बिनसि जाए छिन में।", hindi:"मन रे तन कागद का पुतला,\\nलागे बूंद बिनसि जाए छिन में।", poet:"Kabir Das", poetId:2, form:"Doha", likes:34200, isRajanQuote:false },
  { id:13, text:"कबीरा खड़ा बाज़ार में, मांगे सबकी खैर।\\nना काहू से दोस्ती, न काहू से बैर।।", hindi:"कबीरा खड़ा बाज़ार में, मांगे सबकी खैर।\\nना काहू से दोस्ती, न काहू से बैर।।", poet:"Kabir Das", poetId:2, form:"Doha", likes:29400, isRajanQuote:false },
  { id:7, text:"रहिमन धागा प्रेम का, मत तोड़ो चटकाय,\\nटूटे से फिर ना जुड़े, जुड़े गाँठ पड़ जाय।", hindi:"रहिमन धागा प्रेम का, मत तोड़ो चटकाय,\\nटूटे से फिर ना जुड़े, जुड़े गाँठ पड़ जाय।", poet:"Rahim Das", poetId:9, form:"Doha", likes:38500, isRajanQuote:false },
  { id:14, text:"रहिमन पानी राखिये, बिन पानी सब सून।\\nपानी गए न ऊबरै, मोती, मानुष, चून।।", hindi:"रहिमन पानी राखिये, बिन पानी सब सून।\\nपानी गए न ऊबरै, मोती, मानुष, चून।।", poet:"Rahim Das", poetId:9, form:"Doha", likes:31200, isRajanQuote:false },
  { id:8, text:"मेरे तो गिरिधर गोपाल दूसरो न कोई,\\nजाके सिर मोर मुकुट मेरो पति सोई।", hindi:"मेरे तो गिरिधर गोपाल दूसरो न कोई,\\nजाके सिर मोर मुकुट मेरो पति सोई।", poet:"Mirabai", poetId:4, form:"Bhajan", likes:42100, isRajanQuote:false },
  { id:15, text:"पायो जी मैंने राम रतन धन पायो।\\nबस्तु अमोलक दी मेरे सतगुर, कर किरपा अपनायो।", hindi:"पायो जी मैंने राम रतन धन पायो।\\nबस्तु अमोलक दी मेरे सतगुर, कर किरपा अपनायो।", poet:"Mirabai", poetId:4, form:"Bhajan", likes:48500, isRajanQuote:false },
  { id:9, text:"सिंहासन खाली करो कि जनता आती है।", hindi:"सिंहासन खाली करो कि जनता आती है।", poet:"Ramdhari Singh Dinkar", poetId:5, form:"Veer Ras", likes:56000, isRajanQuote:false },
  { id:16, text:"क्षमा शोभती उस भुजंग को जिसके पास गरल हो।\\nउसको क्या जो दंतहीन, विषरहित, विनीत, सरल हो।।", hindi:"क्षमा शोभती उस भुजंग को जिसके पास गरल हो।\\nउसको क्या जो दंतहीन, विषरहित, विनीत, सरल हो।।", poet:"Ramdhari Singh Dinkar", poetId:5, form:"Kavita", likes:45300, isRajanQuote:false },
  { id:10, text:"बैर कराते मंदिर मस्जिद,\\nमेल कराती मधुशाला।", hindi:"बैर कराते मंदिर मस्जिद,\\nमेल कराती मधुशाला।", poet:"Harivansh Rai Bachchan", poetId:3, form:"Kavita", likes:28900, isRajanQuote:false },
  { id:17, text:"मदिरालय जाने को घर से चलता है पीनेवाला,\\n'किस पथ से जाऊँ?' असमंजस में है वह भोलाभाला,\\nअलग-अलग पथ बतलाते सब पर मैं यह बतलाता हूँ -\\n'राह पकड़ तू एक चला चल, पा जाएगा मधुशाला।'", hindi:"मदिरालय जाने को घर से चलता है पीनेवाला,\\n'किस पथ से जाऊँ?' असमंजस में है वह भोलाभाला,\\nअलग-अलग पथ बतलाते सब पर मैं यह बतलाता हूँ -\\n'राह पकड़ तू एक चला चल, पा जाएगा मधुशाला।'", poet:"Harivansh Rai Bachchan", poetId:3, form:"Kavita", likes:51200, isRajanQuote:false },
  { id:18, text:"आने वाला पल जाने वाला है,\\nहो सके तो इसमें ज़िन्दगी बिता दो,\\nपल जो ये जाने वाला है।", hindi:"आने वाला पल जाने वाला है,\\nहो सके तो इसमें ज़िन्दगी बिता दो,\\nपल जो ये जाने वाला है।", poet:"Gulzar", poetId:6, form:"Nazm", likes:67000, isRajanQuote:false },
  { id:19, text:"हाथ छूटे भी तो रिश्ते नहीं छोड़ा करते,\\nवक्त की शाख से लम्हें नहीं तोड़ा करते।", hindi:"हाथ छूटे भी तो रिश्ते नहीं छोड़ा करते,\\nवक्त की शाख से लम्हें नहीं तोड़ा करते।", poet:"Gulzar", poetId:6, form:"Sher", likes:54200, isRajanQuote:false },
  { id:20, text:"मैं नीर भरी दु:ख की बदली!\\nविस्तृत नभ का कोई कोना,\\nमेरा न कभी अपना होना।", hindi:"मैं नीर भरी दु:ख की बदली!\\nविस्तृत नभ का कोई कोना,\\nमेरा न कभी अपना होना।", poet:"Mahadevi Verma", poetId:7, form:"Kavita", likes:31500, isRajanQuote:false },
  { id:21, text:"वियोगी होगा पहला कवि,\\nआह से उपजा होगा गान,\\nउमड़ कर आंखों से चुपचाप\\nबही होगी कविता अनजान।", hindi:"वियोगी होगा पहला कवि,\\nआह से उपजा होगा गान,\\nउमड़ कर आंखों से चुपचाप\\nबही होगी कविता अनजान।", poet:"Sumitranandan Pant", poetId:8, form:"Kavita", likes:27800, isRajanQuote:false },
  { id:22, text:"दुख ही जीवन की कथा रही,\\nक्या कहूँ आज, जो नहीं कही!", hindi:"दुख ही जीवन की कथा रही,\\nक्या कहूँ आज, जो नहीं कही!", poet:"Nirala", poetId:10, form:"Kavita", likes:33100, isRajanQuote:false },
  { id:23, text:"नारी! तुम केवल श्रद्धा हो\\nविश्वास-रजत-नग पगतल में,\\nपीयूष-स्रोत-सी बहा करो\\nजीवन के सुंदर समतल में।", hindi:"नारी! तुम केवल श्रद्धा हो\\nविश्वास-रजत-नग पगतल में,\\nपीयूष-स्रोत-सी बहा करो\\nजीवन के सुंदर समतल में।", poet:"Jaishankar Prasad", poetId:11, form:"Mahakavya", likes:46700, isRajanQuote:false },
  { id:24, text:"कश्मीर कोई ऐसा वैसा टुकड़ा नहीं,\\nयह तो भारत माता का मस्तक है।", hindi:"कश्मीर कोई ऐसा वैसा टुकड़ा नहीं,\\nयह तो भारत माता का मस्तक है।", poet:"Dr. Hariom Panwar", poetId:12, form:"Veer Ras", likes:39900, isRajanQuote:false },
  { id:11, text:"Truth does not need many words -\\nit only needs one honest moment.", hindi:"सत्य को कई शब्दों की ज़रूरत नहीं -\\nउसे बस एक ईमानदार पल चाहिए।", poet:"Rajan Rai", poetId:1, form:"Aphorism", likes:7900, isRajanQuote:true },
  { id:12, text:"The strongest man is not the one who never falls -\\nit is the one who always rises.", hindi:"सबसे मजबूत इंसान वो नहीं जो कभी गिरता नहीं -\\nबल्कि वो है जो हमेशा उठता है।", poet:"Rajan Rai", poetId:1, form:"Aphorism", likes:9100, isRajanQuote:true }
]`;

const updatedQuotes = `[
  { id:1, text:"A man can do anything, when he realises he is a man.", hindi:"एक इंसान सब कुछ कर सकता है, जब वो जान ले कि वो इंसान है।", author:"Rajan Rai", isFounder:true },
  { id:2, text:"Silence is the loudest answer the soul ever gives.", hindi:"खामोशी वो सबसे ऊँची आवाज़ है जो आत्मा कभी देती है।", author:"Rajan Rai", isFounder:true },
  { id:3, text:"Every storm within you is just a sunrise waiting to break.", hindi:"तुम्हारे भीतर का हर तूफ़ान बस एक सूर्योदय है।", author:"Rajan Rai", isFounder:true },
  { id:4, text:"The mind that questions itself is already wiser than most.", hindi:"वो मन जो खुद से सवाल करता है वो पहले से ही अधिकांश से बुद्धिमान है।", author:"Rajan Rai", isFounder:true },
  { id:5, text:"Love is not what you feel - it is what you become.", hindi:"प्रेम वो नहीं जो तुम महसूस करते हो - प्रेम वो है जो तुम बन जाते हो।", author:"Rajan Rai", isFounder:true },
  { id:6, text:"Truth does not need many words - it only needs one honest moment.", hindi:"सत्य को कई शब्दों की ज़रूरत नहीं - उसे बस एक ईमानदार पल चाहिए।", author:"Rajan Rai", isFounder:true },
  { id:7, text:"The strongest man is not the one who never falls - it is the one who always rises.", hindi:"सबसे मजबूत इंसान वो है जो हमेशा उठता है।", author:"Rajan Rai", isFounder:true },
  { id:101, text:"जहाँ कोई तुम्हारा सम्मान न करे, वहाँ कभी मत जाओ।", hindi:"जहाँ कोई तुम्हारा सम्मान न करे, वहाँ कभी मत जाओ।", author:"Kabir Das", isFounder:false },
  { id:102, text:"जो है भार वही है उठाना, जब तक जियो तब तक यही काम।", hindi:"जो है भार वही है उठाना, जब तक जियो तब तक यही काम।", author:"Harivansh Rai Bachchan", isFounder:false },
  { id:103, text:"कोई दीवाना कहता है, कोई पागल समझता है।", hindi:"कोई दीवाना कहता है, कोई पागल समझता है।", author:"Gulzar", isFounder:false },
  { id:104, text:"कलम देश की बड़ी शक्ति है, भाव जगाने वाली।", hindi:"कलम देश की बड़ी शक्ति है, भाव जगाने वाली।", author:"Ramdhari Singh Dinkar", isFounder:false }
]`;

// Replace FB_POETS
const poetsRegex = /const\\s+FB_POETS\\s*=\\s*\\[[\\s\\S]*?\\];/;
content = content.replace(poetsRegex, `const FB_POETS = ${updatedPoets};`);

// Replace FB_POEMS
const poemsRegex = /const\\s+FB_POEMS\\s*=\\s*\\[[\\s\\S]*?\\];/;
content = content.replace(poemsRegex, `const FB_POEMS = ${updatedPoems};`);

// Replace FB_QUOTES
const quotesRegex = /const\\s+FB_QUOTES\\s*=\\s*\\[[\\s\\S]*?\\];/;
content = content.replace(quotesRegex, `const FB_QUOTES = ${updatedQuotes};`);

fs.writeFileSync(apiPath, content, 'utf8');
console.log('Successfully expanded FB_POETS, FB_POEMS, and FB_QUOTES in api.js!');
